name = "vkmuzpremium-stars-payments"
main = "worker.js"
compatibility_date = "2026-10-02"
workers_dev = true

[vars]
MINI_APP_URL = "https://vkmuzpremium-stars.shamsiddinov07xz.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "vkmuzpremium_stars"
database_id = "REPLACE_WITH_DATABASE_ID"
